/**
 * i18n dictionary for the HTML report.
 * All user-visible strings go through t() so language switching is trivial.
 */
export type Locale = 'zh' | 'en'

export interface Dict {
  title: string
  subtitle: string
  generatedAt: string
  repo: string
  head: string
  version: string
  elapsed: string
  themeToggle: string
  langToggle: string
  fontSmall: string
  fontDefault: string
  fontLarge: string
  lineCompact: string
  lineDefault: string
  lineLoose: string
  churnTitle: string
  churnDesc: string
  contributorsTitle: string
  contributorsDesc: string
  bugsTitle: string
  bugsDesc: string
  velocityTitle: string
  velocityDesc: string
  firefightingTitle: string
  firefightingDesc: string
  crossTitle: string
  crossDesc: string
  gradeA: string
  gradeB: string
  gradeC: string
  topShare: string
  activeRatio: string
  recentAvg: string
  previousAvg: string
  perMonth: string
  totalEvents: string
  criticalFiles: string
  warningFiles: string
  noIssues: string
  noData: string
  fileLabel: string
  countLabel: string
  dateLabel: string
  hashLabel: string
  subjectLabel: string
  monthLabel: string
  commitsLabel: string
  riskCritical: string
  riskWarning: string
  riskNormal: string
  footerNote: string
}

export const dict: Record<Locale, Dict> = {
  en: {
    title: 'git-xray report',
    subtitle: 'Five git commands that diagnose a new codebase before you open a single file.',
    generatedAt: 'Generated at',
    repo: 'Repository',
    head: 'HEAD',
    version: 'Tool version',
    elapsed: 'Elapsed',
    themeToggle: 'Toggle theme',
    langToggle: '中文 / EN',
    fontSmall: 'A−',
    fontDefault: 'A',
    fontLarge: 'A+',
    lineCompact: 'Compact',
    lineDefault: 'Standard',
    lineLoose: 'Loose',
    churnTitle: 'Churn Hotspots',
    churnDesc: 'Most-changed files in the analyzed window. The file at the top is almost always the one people warn you about.',
    contributorsTitle: 'Who Built This',
    contributorsDesc: 'Contributors ranked by commit count, cross-referenced against a recent 6-month activity window.',
    bugsTitle: 'Where Do Bugs Cluster',
    bugsDesc: 'Files that appear in commits with bug-related keywords (fix|bug|broken). Compare against churn hotspots above.',
    velocityTitle: 'Accelerating or Dying',
    velocityDesc: 'Monthly commit count across the entire history. Watch for shape: drops, spikes, long declines.',
    firefightingTitle: 'Firefighting Frequency',
    firefightingDesc: 'Commits matching revert|hotfix|emergency|rollback. Frequent reverts suggest deploy-pipeline issues.',
    crossTitle: 'Cross-Risk Files',
    crossDesc: 'Files appearing in BOTH top churn and top bug lists — your highest-risk code.',
    gradeA: 'A',
    gradeB: 'B',
    gradeC: 'C',
    topShare: 'Top share',
    activeRatio: 'Active (6mo)',
    recentAvg: 'Recent avg (6mo)',
    previousAvg: 'Previous avg',
    perMonth: 'Avg per month',
    totalEvents: 'Total events',
    criticalFiles: 'Critical',
    warningFiles: 'Warning',
    noIssues: 'No overlapping risk files. Healthy signal.',
    noData: 'No data in this window.',
    fileLabel: 'File',
    countLabel: 'Commits',
    dateLabel: 'Date',
    hashLabel: 'Hash',
    subjectLabel: 'Subject',
    monthLabel: 'Month',
    commitsLabel: 'Commits',
    riskCritical: 'CRITICAL',
    riskWarning: 'WARNING',
    riskNormal: 'OK',
    footerNote: 'Generated by git-xray · methodology inspired by Ally Piechowski',
  },
  zh: {
    title: 'git-xray 报告',
    subtitle: '打开任何代码之前，先用 5 条 git 命令诊断一个新代码库。',
    generatedAt: '生成时间',
    repo: '仓库',
    head: '当前提交',
    version: '工具版本',
    elapsed: '耗时',
    themeToggle: '切换主题',
    langToggle: 'EN / 中文',
    fontSmall: 'A−',
    fontDefault: 'A',
    fontLarge: 'A+',
    lineCompact: '紧凑',
    lineDefault: '标准',
    lineLoose: '宽松',
    churnTitle: '高频变更文件',
    churnDesc: '分析窗口内变更次数最多的文件。最上面的几乎总是别人提醒你"小心点"的那个。',
    contributorsTitle: '谁构建了它',
    contributorsDesc: '按提交数排名的贡献者，并与最近 6 个月的活跃窗口交叉对比。',
    bugsTitle: 'Bug 聚集地',
    bugsDesc: '出现在含 fix|bug|broken 关键字的提交中的文件。请与上方的变更热点对照。',
    velocityTitle: '加速还是衰退',
    velocityDesc: '整个历史中按月统计的提交数。注意形状：骤降、突发高峰、长期下滑。',
    firefightingTitle: '救火频率',
    firefightingDesc: '匹配 revert|hotfix|emergency|rollback 的提交。频繁回滚通常暗示部署流程问题。',
    crossTitle: '交叉风险文件',
    crossDesc: '同时出现在高频变更和 Bug 列表中的文件 —— 风险最高的代码。',
    gradeA: 'A',
    gradeB: 'B',
    gradeC: 'C',
    topShare: '头部占比',
    activeRatio: '活跃贡献者（近 6 个月）',
    recentAvg: '近 6 个月平均',
    previousAvg: '前 6 个月平均',
    perMonth: '月均事件',
    totalEvents: '事件总数',
    criticalFiles: '严重',
    warningFiles: '警告',
    noIssues: '没有交叉风险文件，信号健康。',
    noData: '该窗口内无数据。',
    fileLabel: '文件',
    countLabel: '提交数',
    dateLabel: '日期',
    hashLabel: '哈希',
    subjectLabel: '主题',
    monthLabel: '月份',
    commitsLabel: '提交数',
    riskCritical: '严重',
    riskWarning: '警告',
    riskNormal: '正常',
    footerNote: '由 git-xray 生成 · 方法论受 Ally Piechowski 启发',
  },
}
