/**
 * Generated by tsnapi — public API snapshot of `@condorhero/git-xray`
 */
// #region Interfaces
export interface BugEntry {
  file: string;
  count: number;
}
export interface BugsReport {
  files: BugEntry[];
  totalCommits: number;
  since: string;
}
export interface ChurnEntry {
  file: string;
  count: number;
}
export interface ChurnReport {
  files: ChurnEntry[];
  totalFiles: number;
  totalCommits: number;
  since: string;
}
export interface ContributorEntry {
  name: string;
  email: string;
  commits: number;
  share: number;
  active: boolean;
}
export interface ContributorsReport {
  contributors: ContributorEntry[];
  totalCommits: number;
  topShare: number;
  activeCount: number;
  totalCount: number;
  grade: Grade;
}
export interface CrossRiskReport {
  critical: RiskFile[];
  warning: RiskFile[];
}
export interface Dict {
  title: string;
  subtitle: string;
  generatedAt: string;
  repo: string;
  head: string;
  version: string;
  elapsed: string;
  themeToggle: string;
  langToggle: string;
  fontSmall: string;
  fontDefault: string;
  fontLarge: string;
  lineCompact: string;
  lineDefault: string;
  lineLoose: string;
  churnTitle: string;
  churnDesc: string;
  contributorsTitle: string;
  contributorsDesc: string;
  bugsTitle: string;
  bugsDesc: string;
  velocityTitle: string;
  velocityDesc: string;
  firefightingTitle: string;
  firefightingDesc: string;
  crossTitle: string;
  crossDesc: string;
  gradeA: string;
  gradeB: string;
  gradeC: string;
  topShare: string;
  activeRatio: string;
  recentAvg: string;
  previousAvg: string;
  perMonth: string;
  totalEvents: string;
  criticalFiles: string;
  warningFiles: string;
  noIssues: string;
  noData: string;
  fileLabel: string;
  countLabel: string;
  dateLabel: string;
  hashLabel: string;
  subjectLabel: string;
  monthLabel: string;
  commitsLabel: string;
  riskCritical: string;
  riskWarning: string;
  riskNormal: string;
  footerNote: string;
}
export interface FirefightingEvent {
  hash: string;
  subject: string;
  date: string;
  month: string;
}
export interface FirefightingReport {
  events: FirefightingEvent[];
  byMonth: VelocityMonth[];
  perMonthAvg: number;
  grade: Grade;
}
export interface RepoMeta {
  path: string;
  name: string;
  headShort: string;
  headFull: string;
  generatedAt: string;
  generatedAtLocal: string;
  toolVersion: string;
  elapsedMs: number;
}
export interface ReportData {
  meta: RepoMeta;
  churn: ChurnReport;
  contributors: ContributorsReport;
  bugs: BugsReport;
  velocity: VelocityReport;
  firefighting: FirefightingReport;
  cross: CrossRiskReport;
}
export interface RiskFile {
  file: string;
  churnCount: number;
  bugCount: number;
  risk: RiskLevel;
}
export interface VelocityMonth {
  month: string;
  count: number;
}
export interface VelocityReport {
  history: VelocityMonth[];
  recentAvg: number;
  previousAvg: number;
  ratio: number | undefined;
  grade: Grade;
}
// #endregion

// #region Types
export type Grade = 'A' | 'B' | 'C';
export type Locale = 'zh' | 'en';
export type RiskLevel = 'critical' | 'warning' | 'normal';
// #endregion

// #region Classes
export declare class GitError extends Error {
  readonly stderr: string;
  readonly code: number | null;
  constructor(_: string, _: string, _: number | null);
}
// #endregion

// #region Functions
export declare function analyzeBugs(_: string, _?: {
  since?: string;
  top?: number;
}): Promise<BugsReport>;
export declare function analyzeChurn(_: string, _?: {
  since?: string;
  top?: number;
}): Promise<ChurnReport>;
export declare function analyzeContributors(_: string): Promise<ContributorsReport>;
export declare function analyzeFirefighting(_: string, _?: {
  since?: string;
}): Promise<FirefightingReport>;
export declare function analyzeVelocity(_: string): Promise<VelocityReport>;
export declare function collectRepoMeta(_: string, _: string, _?: string): Promise<RepoInfo>;
export declare function crossReference(_: ChurnReport, _: BugsReport): CrossRiskReport;
export declare function fileIcon(_: string): string;
export declare function getRepoRoot(_: string): Promise<string>;
export declare function renderHtml(_: ReportData, _?: Locale): string;
export declare function renderTerminal(_: ReportData): string;
export declare function runGit(_: string[], _: RunGitOptions): Promise<string>;
export declare function runReport(_: RunOptions): Promise<ReportData>;
// #endregion

// #region Variables
export declare const dict: Record<Locale, Dict>;
// #endregion